process and signals

diff --git a/0x05-processes_and_signals/101-manage_my_process b/0x05-processes_and_signals/101-manage_my_process
--- a/0x05-processes_and_signals/101-manage_my_process
+++ b/0x05-processes_and_signals/101-manage_my_process
@@ -1,31 +1,34 @@
 #!/usr/bin/env bash
-# The init scripts that manage manage_my_process
+# The init script that manages manage_my_process
 
 if [ "$1" == "start" ]; then
     ./manage_my_process &
-    echo $! > /var/run/my_process.pid
-    echo "manage_my_process started"
+    if [ $? -eq 0 ]; then
+        echo $! > /var/run/my_process.pid
+        echo "manage_my_process started"
+    else
+        echo "Failed to start manage_my_process"
+    fi
 
 elif [ "$1" == "stop" ]; then
     if [ -e /var/run/my_process.pid ]; then
         pid=$(cat /var/run/my_process.pid)
-        kill $pid
-        rm /var/run/my_process.pid
-        echo "manage_my_process stopped"
+        if ps -p $pid > /dev/null; then
+            kill $pid
+            rm /var/run/my_process.pid
+            echo "manage_my_process stopped"
+        else
+            echo "manage_my_process is not running"
+        fi
     else
         echo "manage_my_process is not running"
     fi
 
 elif [ "$1" == "restart" ]; then
-    if [ -e /var/run/my_process.pid ]; then
-        pid=$(cat /var/run/my_process.pid)
-        kill $pid
-        rm /var/run/my_process.pid
-    fi
-    ./manage_my_process &
-    echo $! > /var/run/my_process.pid
-    echo "manage_my_process restarted"
+    $0 stop
+    $0 start
 
 else
-    echo "Usage: manage_my_process {start|stop|restart}"
+    echo "Usage: $0 {start|stop|restart}"
+    exit 1
 fi
